image: ghcr.io/siemens/kas/kas-isar:2.6.2

variables:
  GIT_STRATEGY: clone

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - for TARGET in $(grep "\"mc:" Kconfig | sed 's/.*"\([^"]\+\)"/\1/'); do
          KAS_TARGET="${KAS_TARGET} ${TARGET}";
      done
    - export KAS_TARGET
    - cd ..
    - kas build jailhouse-images/kas.yml
    - kas build jailhouse-images/kas.yml:jailhouse-images/opt-latest.yml:jailhouse-images/opt-rt.yml
