image: kasproject/kas-isar:2.0

variables:
  GIT_STRATEGY: clone

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - while read MACHINE DESCRIPTION; do
          KAS_TARGET="${KAS_TARGET} mc:${MACHINE}-jailhouse-demo:demo-image";
      done < images.list
    - export KAS_TARGET
    - cd ..
    - kas build jailhouse-images/kas.yml
    - KAS_TARGET=$(echo $KAS_TARGET|sed 's/mc:rpi4-jailhouse-demo:demo-image//')
    - kas build jailhouse-images/kas.yml:jailhouse-images/opt-latest.yml:jailhouse-images/opt-rt.yml
